spring:
  jackson:
    data-format: yyyy-MM-dd
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用数值timestamp表示日期
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.example: TRACE